### ISSUE TITLE
Sample EMD-files from FDES

### ISSUE THREAD

**Issue by magnunor** [woutervandenbroek/FDES#1]
I'm working on implementing direct file support for EMD-files in HyperSpy, which is an open source Python project for visualizing/processing multidimensional data. Mostly TEM-spectroscopy (EDS/EELS), but also STEM/TEM image stacks: https://github.com/hyperspy/hyperspy https://github.com/hyperspy/hyperspy/issues/699

I've been in contact with Colin Ophus about getting some EMD-sample files, but I'm also interested in getting some EMD-files generated using FDES, to make sure the file support works for all EMD-files.

I could generate these files using FDES on my own system, but unfortunately I don't have access to a NVIDIA GPU at the moment.

**Comment by woutervandenbroek** [comment]
Dear Magnus,

Thanks for taking an interest in FDES. Are you asking me to send you one of
the EMD files we have?, because I can easily do that if you want.

Best regards,
Wouter.

**Comment by magnunor** [comment]
Yes. The easiest way would probably be to put it online somewhere. Alternatively sending it to me directly as an email.

**Comment by woutervandenbroek** [comment]
Dear Magnus,

There is one in the attachment. My apologies for the late reply, but I'm in
the middle of moving house.

Best regards,
Wouter.
